/**
 * Builds the self-contained browser tool by inlining js/pads-parser.js
 * into js/pads-tool.template.html.
 *
 * Usage: node js/build-tool.js   ->  writes js/pads-tool.html
 *
 * (Only needed after editing the parser or the template; the committed
 * js/pads-tool.html is already built and needs no tooling to use.)
 */
"use strict";

var fs = require("fs");
var path = require("path");

var parserSrc = fs.readFileSync(path.join(__dirname, "pads-parser.js"), "utf8");
var template = fs.readFileSync(path.join(__dirname, "pads-tool.template.html"), "utf8");

if (parserSrc.indexOf("</script") >= 0) {
  throw new Error("parser source contains '</script' and cannot be inlined safely");
}

var marker = "//__PADS_PARSER_SOURCE__";
if (template.indexOf(marker) < 0) throw new Error("marker not found in template");

var banner =
  "// ==== inlined js/pads-parser.js (generated by js/build-tool.js — do not edit here) ====\n";
var out = template.replace(marker, function () { return banner + parserSrc; });

var outPath = path.join(__dirname, "pads-tool.html");
fs.writeFileSync(outPath, out);
console.log("wrote " + outPath + " (" + out.length + " bytes)");
